version: '3.7'

services:
  nginx-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-prod
    restart: always
    network_mode: "host"
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - 80:80

networks: 
  default: 
    external: 
      name: netplanner-network